services:
  journal_api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PG_URL=postgres://user:password@db:5432/journal
      - JWT_SECRET=secret
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: journal
